#!/bin/bash

mkdir -p ../../.dist/web_interface

lessc style.less ../../.dist/web_interface/style.css
babel web_interface.es2015 --out-file ../../.dist/web_interface/index.js

cp index.html ../../.dist/web_interface/index.html